export const buildersManagerAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [{ internalType: "address", name: "_attester", type: "address" }],
    name: "AlreadyUpdated",
    type: "error",
  },
  { inputs: [], name: "AlreadyVerified", type: "error" },
  { inputs: [], name: "AlreadyVouched", type: "error" },
  { inputs: [], name: "CycleNotReady", type: "error" },
  { inputs: [], name: "IdAttestationRequired", type: "error" },
  { inputs: [], name: "InvalidIdAttestation", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "InvalidLength", type: "error" },
  { inputs: [], name: "InvalidParameter", type: "error" },
  { inputs: [], name: "InvalidProjectUid", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "SettingsNotSet", type: "error" },
  { inputs: [], name: "YieldNoProjects", type: "error" },
  { inputs: [], name: "ZeroValue", type: "error" },
  { anonymous: false, inputs: [], name: "EIP712DomainChanged", type: "event" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_attester",
        type: "address",
      },
      { indexed: true, internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "OpFoundationAttesterUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "_param",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "ParameterModified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_project",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_attestation",
        type: "bytes32",
      },
    ],
    name: "ProjectReachedMinVouches",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "_approvalAttestation",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
    ],
    name: "ProjectValidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_claimer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "_identityAttestation",
        type: "bytes32",
      },
    ],
    name: "VoterValidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_voter",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_project",
        type: "address",
      },
      { indexed: true, internalType: "bytes32", name: "_uid", type: "bytes32" },
    ],
    name: "VouchRecorded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_yield",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "_projects",
        type: "address[]",
      },
    ],
    name: "YieldDistributed",
    type: "event",
  },
  {
    inputs: [],
    name: "EAS",
    outputs: [{ internalType: "contract IEAS", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OP_SCHEMA_599",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OP_SCHEMA_638",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TOKEN",
    outputs: [
      { internalType: "contract BuildersDollar", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_attestersToUpdate",
        type: "address[]",
      },
      { internalType: "bool[]", name: "_statuses", type: "bool[]" },
    ],
    name: "batchUpdateOpFoundationAttesters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentProjectUids",
    outputs: [{ internalType: "bytes32[]", name: "_uids", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentProjects",
    outputs: [
      { internalType: "address[]", name: "_projects", type: "address[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "distributeYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { internalType: "bytes1", name: "fields", type: "bytes1" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "version", type: "string" },
      { internalType: "uint256", name: "chainId", type: "uint256" },
      { internalType: "address", name: "verifyingContract", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "uint256[]", name: "extensions", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_uid", type: "bytes32" }],
    name: "eligibleProject",
    outputs: [{ internalType: "address", name: "_project", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_project", type: "address" }],
    name: "eligibleProjectByUid",
    outputs: [{ internalType: "bytes32", name: "_uid", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_voter", type: "address" }],
    name: "eligibleVoter",
    outputs: [
      { internalType: "bool", name: "_isEligibleAndVouched", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "address", name: "_eas", type: "address" },
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_version", type: "string" },
      {
        components: [
          { internalType: "uint64", name: "cycleLength", type: "uint64" },
          {
            internalType: "uint64",
            name: "lastClaimedTimestamp",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "currentSeasonExpiry",
            type: "uint64",
          },
          { internalType: "uint256", name: "seasonDuration", type: "uint256" },
          { internalType: "uint256", name: "minVouches", type: "uint256" },
          {
            internalType: "address[]",
            name: "optimismFoundationAttesters",
            type: "address[]",
          },
        ],
        internalType: "struct IBuildersManager.BuilderManagerSettings",
        name: "__settings",
        type: "tuple",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_param", type: "bytes32" },
      { internalType: "uint256", name: "_value", type: "uint256" },
    ],
    name: "modifyParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_attester", type: "address" }],
    name: "optimismFoundationAttester",
    outputs: [{ internalType: "bool", name: "_isEligible", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "optimismFoundationAttesters",
    outputs: [
      { internalType: "address[]", name: "_opAttesters", type: "address[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_project", type: "address" }],
    name: "projectToExpiry",
    outputs: [{ internalType: "uint256", name: "_expiry", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_project", type: "address" }],
    name: "projectToVouchers",
    outputs: [
      { internalType: "address[]", name: "_vouchers", type: "address[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_project", type: "address" }],
    name: "projectToVouches",
    outputs: [
      { internalType: "uint256", name: "_totalVouches", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "settings",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "cycleLength", type: "uint64" },
          {
            internalType: "uint64",
            name: "lastClaimedTimestamp",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "fundingExpiry",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "seasonStart",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "seasonDuration",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "minVouches",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "optimismFoundationAttesters",
            type: "address[]",
          },
        ],
        internalType: "struct IBuildersManager.BuilderManagerSettings",
        name: "__settings",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_attester", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "updateOpFoundationAttester",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_identityAttestation",
        type: "bytes32",
      },
    ],
    name: "validateOptimismVoter",
    outputs: [{ internalType: "bool", name: "_verified", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_voter", type: "address" },
      { internalType: "bytes32", name: "_uid", type: "bytes32" },
    ],
    name: "voterToProjectVouch",
    outputs: [{ internalType: "bool", name: "_vouched", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_uid", type: "bytes32" },
      {
        internalType: "bytes32",
        name: "_identityAttestation",
        type: "bytes32",
      },
    ],
    name: "vouch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_uid", type: "bytes32" }],
    name: "vouch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
